export const EVENTS = {
  BEGINNING_ADDED: 'BEGINNING_ADDED',
  BEGINNING_UPDATED: 'BEGINNING_UPDATED',

  USER_ADDED: 'USER_ADDED',
  USER_UPDATED: 'USER_UPDATED',
  USER_FORGOT_PASSWORD: 'USER_FORGOT_PASSWORD',
} as const;
