name: AYNEED

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

jobs:
  install-build-eslint-test:
    name: Run unit tests and eslint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Installation dependencies
        run: yarn install

      - name: Run eslint
        run: yarn run lint

      - name: Backend api - testing
        working-directory: backend-api
        run: |
          yarn run build
          yarn run test

      - name: Frontend web - testing
        working-directory: frontend-web
        run: yarn run test
