name: AYNEED

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

jobs:
  test:
    name: Run unit tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Installation dependencies
        run: yarn install

      - name: Backend api testing
        working-directory: backend-api
        run: |
          yarn run build
          yarn run test
